/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c0c9c1",
        "secondary-fixed-dim": "#e9c349",
        "inverse-surface": "#2d3133",
        "on-secondary-fixed": "#241a00",
        "primary-fixed-dim": "#9cd2b5",
        "on-secondary": "#ffffff",
        "background": "#f7f9fb",
        "inverse-primary": "#9cd2b5",
        "surface-container-high": "#e6e8ea",
        "tertiary": "#102620",
        "on-primary": "#ffffff",
        "primary": "#002819",
        "primary-fixed": "#b8efd0",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary": "#ffffff",
        "surface-tint": "#356850",
        "error-container": "#ffdad6",
        "surface-container-low": "#f2f4f6",
        "on-primary-container": "#77ac90",
        "on-error": "#ffffff",
        "surface": "#f7f9fb",
        "on-tertiary-container": "#8ea69d",
        "on-tertiary-fixed": "#091f19",
        "tertiary-fixed": "#cfe8dd",
        "surface-container-highest": "#e0e3e5",
        "on-surface": "#191c1e",
        "surface-container": "#eceef0",
        "on-tertiary-fixed-variant": "#354b43",
        "on-background": "#191c1e",
        "outline": "#717973",
        "tertiary-fixed-dim": "#b3ccc2",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#263c35",
        "secondary-fixed": "#ffe088",
        "on-secondary-container": "#745c00",
        "on-surface-variant": "#404943",
        "surface-variant": "#e0e3e5",
        "on-primary-fixed": "#002114",
        "secondary-container": "#fed65b",
        "on-primary-fixed-variant": "#1b503a",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#574500",
        "secondary": "#735c00",
        "primary-container": "#06402b",
        "surface-bright": "#f7f9fb",
        "error": "#ba1a1a",
        "surface-dim": "#d8dadc",
        charity: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
        },
        dark: {
          900: '#0f172a',
          800: '#1e293b',
        }
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
